apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-deployment
  labels:
    app: cafe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cafe
  template:
    metadata:
      labels:
        app: cafe
    spec:
      containers:
      - name: cafe
        image: rintajom/cafe.project:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cafe-service
spec:
  type: NodePort
  selector:
    app: cafe
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007