name: CI

on:
  push:
    branches: [ "M_actions" ]
  pull_request:
    branches: [ "M_actions" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
	  - name: checkout code
        uses: actions/checkout@v4
	  
	  - name: Set up JDK 17
	  	uses: actions/setup-java@v3
	  	with:
	  		java-version: '17'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

	  - name: Build with Maven
	  	run: mvn clean install
		
	  - name: Echo build status
		run: echo "Build and tests completed."
