name: CI

on:
  push:
    branches: 
      - M_actions
  pull_request:
    branches: 
      - M_actions

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'  # You can also use 'temurin', 'zulu', etc.

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Build with Maven
        run: mvn clean install

      - name: Echo build status
        run: echo "Build and tests completed."
